addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.192.192.192
kind: EndpointSlice
metadata:
  labels: null
  name: cilium-ingress
  namespace: kube-network
ports:
- port: 9999
