apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium-agent.kube-network.service.yaml
- cilium-agent.kube-network.servicemonitor.yaml
- cilium-ca.kube-network.secret.yaml
- cilium-config-agent.kube-network.role.yaml
- cilium-config-agent.kube-network.rolebinding.yaml
- cilium-config.kube-network.configmap.yaml
- cilium-dynamic-metrics-config.kube-network.configmap.yaml
- cilium-envoy-config.kube-network.configmap.yaml
- cilium-envoy.kube-network.daemonset.yaml
- cilium-envoy.kube-network.service.yaml
- cilium-envoy.kube-network.serviceaccount.yaml
- cilium-envoy.kube-network.servicemonitor.yaml
- cilium-ingress-secrets.kube-network.role.yaml
- cilium-ingress.kube-network.endpointslice.yaml
- cilium-ingress.kube-network.service.yaml
- cilium-node-init.kube-network.daemonset.yaml
- cilium-operator-ingress-secrets.kube-network.role.yaml
- cilium-operator-ingress-secrets.kube-network.rolebinding.yaml
- cilium-operator-tlsinterception-secrets.kube-network.role.yaml
- cilium-operator-tlsinterception-secrets.kube-network.rolebinding.yaml
- cilium-operator-ztunnel.kube-network.role.yaml
- cilium-operator-ztunnel.kube-network.rolebinding.yaml
- cilium-operator..clusterrole.yaml
- cilium-operator..clusterrolebinding.yaml
- cilium-operator.kube-network.deployment.yaml
- cilium-operator.kube-network.service.yaml
- cilium-operator.kube-network.serviceaccount.yaml
- cilium-operator.kube-network.servicemonitor.yaml
- cilium-secrets.kube-network.rolebinding.yaml
- cilium-tlsinterception-secrets.kube-network.role.yaml
- cilium-tlsinterception-secrets.kube-network.rolebinding.yaml
- cilium..clusterrole.yaml
- cilium..clusterrolebinding.yaml
- cilium..ingressclass.yaml
- cilium.kube-network.daemonset.yaml
- cilium.kube-network.serviceaccount.yaml
- hubble-dashboard.kube-network.configmap.yaml
- hubble-dns-namespace.kube-network.configmap.yaml
- hubble-l7-http-metrics-by-workload.kube-network.configmap.yaml
- hubble-metrics.kube-network.service.yaml
- hubble-network-overview-namespace.kube-network.configmap.yaml
- hubble-peer.kube-network.service.yaml
- hubble-relay-client-certs.kube-network.secret.yaml
- hubble-relay-config.kube-network.configmap.yaml
- hubble-relay-metrics.kube-network.service.yaml
- hubble-relay.kube-network.deployment.yaml
- hubble-relay.kube-network.service.yaml
- hubble-relay.kube-network.serviceaccount.yaml
- hubble-relay.kube-network.servicemonitor.yaml
- hubble-server-certs.kube-network.secret.yaml
- hubble-ui-nginx.kube-network.configmap.yaml
- hubble-ui..clusterrole.yaml
- hubble-ui..clusterrolebinding.yaml
- hubble-ui.kube-network.deployment.yaml
- hubble-ui.kube-network.service.yaml
- hubble-ui.kube-network.serviceaccount.yaml
- hubble.kube-network.servicemonitor.yaml
- k8s-cp-service-cbdht89hmd.kube-network.configmap.yaml
- kube-network..namespace.yaml
