apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources: []

helmCharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno
  releaseName: kyverno
  namespace: kyverno
  version: v3.6.1
  valuesInline:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 2
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
