apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cleanuppolicies.kyverno.io..customresourcedefinition.yaml
- clustercleanuppolicies.kyverno.io..customresourcedefinition.yaml
- clusterephemeralreports.reports.kyverno.io..customresourcedefinition.yaml
- clusterpolicies.kyverno.io..customresourcedefinition.yaml
- clusterpolicyreports.wgpolicyk8s.io..customresourcedefinition.yaml
- deletingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- ephemeralreports.reports.kyverno.io..customresourcedefinition.yaml
- generatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- globalcontextentries.kyverno.io..customresourcedefinition.yaml
- imagevalidatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- kyverno-admission-controller-metrics.kyverno.pod.yaml
- kyverno-admission-controller.kyverno.deployment.yaml
- kyverno-admission-controller.kyverno.poddisruptionbudget.yaml
- kyverno-admission-controller.kyverno.serviceaccount.yaml
- kyverno-background-controller-metrics.kyverno.service.yaml
- kyverno-background-controller.kyverno.deployment.yaml
- kyverno-background-controller.kyverno.poddisruptionbudget.yaml
- kyverno-background-controller.kyverno.serviceaccount.yaml
- kyverno-cleanup-controller-liveness.kyverno.pod.yaml
- kyverno-cleanup-controller-metrics.kyverno.pod.yaml
- kyverno-cleanup-controller-metrics.kyverno.service.yaml
- kyverno-cleanup-controller-readiness.kyverno.pod.yaml
- kyverno-cleanup-controller.kyverno.deployment.yaml
- kyverno-cleanup-controller.kyverno.poddisruptionbudget.yaml
- kyverno-cleanup-controller.kyverno.service.yaml
- kyverno-cleanup-controller.kyverno.serviceaccount.yaml
- kyverno-metrics.kyverno.configmap.yaml
- kyverno-migrate-resources.kyverno.job.yaml
- kyverno-migrate-resources.kyverno.serviceaccount.yaml
- kyverno-reports-controller-metrics.kyverno.pod.yaml
- kyverno-reports-controller-metrics.kyverno.service.yaml
- kyverno-reports-controller.kyverno.deployment.yaml
- kyverno-reports-controller.kyverno.poddisruptionbudget.yaml
- kyverno-reports-controller.kyverno.serviceaccount.yaml
- kyverno-rm-mutatingwhconfig.kyverno.job.yaml
- kyverno-rm-validatingwhconfig.kyverno.job.yaml
- kyverno-scale-to-zero.kyverno.job.yaml
- kyverno-svc-metrics.kyverno.service.yaml
- kyverno-svc.kyverno.service.yaml
- kyverno.kyverno.configmap.yaml
- kyverno:admission-controller..clusterrole.yaml
- kyverno:admission-controller..clusterrolebinding.yaml
- kyverno:admission-controller.kyverno.role.yaml
- kyverno:admission-controller.kyverno.rolebinding.yaml
- kyverno:admission-controller:core..clusterrole.yaml
- kyverno:admission-controller:view..clusterrolebinding.yaml
- kyverno:background-controller..clusterrole.yaml
- kyverno:background-controller..clusterrolebinding.yaml
- kyverno:background-controller.kyverno.role.yaml
- kyverno:background-controller.kyverno.rolebinding.yaml
- kyverno:background-controller:core..clusterrole.yaml
- kyverno:background-controller:view..clusterrolebinding.yaml
- kyverno:cleanup-controller..clusterrole.yaml
- kyverno:cleanup-controller..clusterrolebinding.yaml
- kyverno:cleanup-controller.kyverno.role.yaml
- kyverno:cleanup-controller.kyverno.rolebinding.yaml
- kyverno:cleanup-controller:core..clusterrole.yaml
- kyverno:migrate-resources..clusterrole.yaml
- kyverno:migrate-resources..clusterrolebinding.yaml
- kyverno:rbac:admin:policies..clusterrole.yaml
- kyverno:rbac:admin:policyreports..clusterrole.yaml
- kyverno:rbac:admin:reports..clusterrole.yaml
- kyverno:rbac:admin:updaterequests..clusterrole.yaml
- kyverno:rbac:view:policies..clusterrole.yaml
- kyverno:rbac:view:policyreports..clusterrole.yaml
- kyverno:rbac:view:reports..clusterrole.yaml
- kyverno:rbac:view:updaterequests..clusterrole.yaml
- kyverno:reports-controller..clusterrole.yaml
- kyverno:reports-controller..clusterrolebinding.yaml
- kyverno:reports-controller.kyverno.role.yaml
- kyverno:reports-controller.kyverno.rolebinding.yaml
- kyverno:reports-controller:core..clusterrole.yaml
- kyverno:reports-controller:view..clusterrolebinding.yaml
- mutatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- namespaceddeletingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- namespacedimagevalidatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- namespacedvalidatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
- policies.kyverno.io..customresourcedefinition.yaml
- policyexceptions.kyverno.io..customresourcedefinition.yaml
- policyexceptions.policies.kyverno.io..customresourcedefinition.yaml
- policyreports.wgpolicyk8s.io..customresourcedefinition.yaml
- updaterequests.kyverno.io..customresourcedefinition.yaml
- validatingpolicies.policies.kyverno.io..customresourcedefinition.yaml
