apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# commonLabels:
#   app.kubernetes.io/part-of: cert-manager
namespace: cert-manager
resources:
- manifests/upstream
patches:
  - target:
      kind: Deployment
      name: cert-manager
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --config=/var/cert-manager/config/config.yaml
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - mountPath: /var/cert-manager/config
            name: config
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - configMap:
              name: cert-manager
            name: config          
    
configMapGenerator:
- files:
    - manifests/configs/config.yaml
  name: cert-manager

  

# +# Source: cert-manager/templates/controller-config.yaml
# +apiVersion: v1
# +kind: ConfigMap
# +metadata:
# +  name: cert-manager
# +  namespace: cert-manager
# +  labels:
# +    app: cert-manager
# +    app.kubernetes.io/name: cert-manager
# +    app.kubernetes.io/instance: myrelease
# +    app.kubernetes.io/component: "controller"
# +    app.kubernetes.io/version: "v1.19.3"
# +    app.kubernetes.io/managed-by: Helm
# +    helm.sh/chart: cert-manager-v1.19.3
# +data:
# +  config.yaml: |
# +    apiVersion: controller.config.cert-manager.io/v1alpha1
# +    featureGates:
# +      ACMEHTTP01IngressPathTypeExact: false
# +    kind: ControllerConfiguration
