apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloack
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: micros-infra
  source:
    path: envs/cluster-1/auth_security/keycloack
    plugin:
      name: kustomize-gcrypt
    repoURL: 'https://github.com/microspray/deployments-infra.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
