apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: harbor
    chart: harbor
    heritage: Helm
    release: harbor
  name: harbor-redis
  namespace: harbor
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: harbor
    component: redis
    release: harbor
  type: ClusterIP
