apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backendconfigpolicies.gateway.kgateway.dev..customresourcedefinition.yaml
- backends.gateway.kgateway.dev..customresourcedefinition.yaml
- directresponses.gateway.kgateway.dev..customresourcedefinition.yaml
- gatewayextensions.gateway.kgateway.dev..customresourcedefinition.yaml
- gatewayparameters.gateway.kgateway.dev..customresourcedefinition.yaml
- httplistenerpolicies.gateway.kgateway.dev..customresourcedefinition.yaml
- kgateway-kgateway-system..clusterrole.yaml
- kgateway-role-kgateway-system..clusterrolebinding.yaml
- kgateway.kgateway-system.deployment.yaml
- kgateway.kgateway-system.service.yaml
- kgateway.kgateway-system.serviceaccount.yaml
- trafficpolicies.gateway.kgateway.dev..customresourcedefinition.yaml
