apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager-2hmdcfttdd.cert-manager.configmap.yaml
- cert-manager-cainjector..clusterrole.yaml
- cert-manager-cainjector..clusterrolebinding.yaml
- cert-manager-cainjector.cert-manager.deployment.yaml
- cert-manager-cainjector.cert-manager.serviceaccount.yaml
- cert-manager-cainjector:leaderelection.cert-manager.role.yaml
- cert-manager-cainjector:leaderelection.cert-manager.rolebinding.yaml
- cert-manager-cluster-view..clusterrole.yaml
- cert-manager-controller-approve:cert-manager-io..clusterrole.yaml
- cert-manager-controller-approve:cert-manager-io..clusterrolebinding.yaml
- cert-manager-controller-certificates..clusterrole.yaml
- cert-manager-controller-certificates..clusterrolebinding.yaml
- cert-manager-controller-certificatesigningrequests..clusterrole.yaml
- cert-manager-controller-certificatesigningrequests..clusterrolebinding.yaml
- cert-manager-controller-challenges..clusterrole.yaml
- cert-manager-controller-challenges..clusterrolebinding.yaml
- cert-manager-controller-clusterissuers..clusterrole.yaml
- cert-manager-controller-clusterissuers..clusterrolebinding.yaml
- cert-manager-controller-ingress-shim..clusterrole.yaml
- cert-manager-controller-ingress-shim..clusterrolebinding.yaml
- cert-manager-controller-issuers..clusterrole.yaml
- cert-manager-controller-issuers..clusterrolebinding.yaml
- cert-manager-controller-orders..clusterrole.yaml
- cert-manager-controller-orders..clusterrolebinding.yaml
- cert-manager-edit..clusterrole.yaml
- cert-manager-startupapicheck.cert-manager.job.yaml
- cert-manager-startupapicheck.cert-manager.serviceaccount.yaml
- cert-manager-startupapicheck:create-cert.cert-manager.role.yaml
- cert-manager-startupapicheck:create-cert.cert-manager.rolebinding.yaml
- cert-manager-tokenrequest.cert-manager.role.yaml
- cert-manager-tokenrequest.cert-manager.rolebinding.yaml
- cert-manager-view..clusterrole.yaml
- cert-manager-webhook..mutatingwebhookconfiguration.yaml
- cert-manager-webhook..validatingwebhookconfiguration.yaml
- cert-manager-webhook.cert-manager.deployment.yaml
- cert-manager-webhook.cert-manager.service.yaml
- cert-manager-webhook.cert-manager.serviceaccount.yaml
- cert-manager-webhook:dynamic-serving.cert-manager.role.yaml
- cert-manager-webhook:dynamic-serving.cert-manager.rolebinding.yaml
- cert-manager-webhook:subjectaccessreviews..clusterrole.yaml
- cert-manager-webhook:subjectaccessreviews..clusterrolebinding.yaml
- cert-manager.cert-manager.deployment.yaml
- cert-manager.cert-manager.podmonitor.yaml
- cert-manager.cert-manager.serviceaccount.yaml
- cert-manager:leaderelection.cert-manager.role.yaml
- cert-manager:leaderelection.cert-manager.rolebinding.yaml
- certificaterequests.cert-manager.io..customresourcedefinition.yaml
- certificates.cert-manager.io..customresourcedefinition.yaml
- challenges.acme.cert-manager.io..customresourcedefinition.yaml
- clusterissuers.cert-manager.io..customresourcedefinition.yaml
- issuers.cert-manager.io..customresourcedefinition.yaml
- orders.acme.cert-manager.io..customresourcedefinition.yaml
